version: '3'
services:

    nginx:
        container_name: "${APP_NAME}_NGINX"
        build:
            context: "./docker/nginx"
        depends_on:
            - php-fpm
        volumes:
            - ${NGINX_SSL_PATH}:/etc/nginx/ssl
            - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
            - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
            - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
        ports:
            - "${NGINX_HOST_HTTPS_PORT}:443"
            - "${NGINX_HOST_HTTP_PORT}:80"
        networks:
            sail:
                ipv4_address: 172.22.0.3

    php-fpm:
        container_name: "${APP_NAME}_PHPFPM"
        build:
            context: "./docker/php-fpm"
        volumes:
            - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
        networks:
            sail:
                ipv4_address: 172.22.0.4
        expose:
            - "9000"

    laravel-horizon:
        container_name: "${APP_NAME}_LARAHORIZON"
        build:
            context: ./docker/laravel-horizon
        volumes:
            - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
            - ./docker/laravel-horizon/supervisord.d:/etc/supervisord.d
        depends_on:
            - php-fpm
        extra_hosts:
            - "dockerhost:${DOCKER_HOST_IP}"
        networks:
            sail:
                ipv4_address: 172.22.0.5

    mysql:
        container_name: "${APP_NAME}_MYSQL"
        image: mysql:8.0.30-debian
        command:
            --default-authentication-plugin=mysql_native_password
            --max_connections=666
            --bind-address=0.0.0.0
            --transaction-isolation=READ-COMMITTED
        restart: unless-stopped
        environment:
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
            - './create-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        ports:
            - "${FORWARD_DB_PORT:-3306}:3306"
        networks:
            sail:
                ipv4_address: 172.22.0.6
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s

    phpmyadmin:
        container_name: "${APP_NAME}_PHPMYADMIN"
        image: phpmyadmin/phpmyadmin
        ports:
            - 8083:80
        environment:
            PMA_HOSTS: mysql
            PMA_PORT: ${FORWARD_DB_PORT:-3306}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-userpass}
            PMA_ARBITRARY: 1
            UPLOAD_LIMIT: 350M
        networks:
            sail:
                ipv4_address: 172.22.0.7

networks:
    sail:
        driver: bridge
        ipam:
            config:
                - subnet: 172.22.0.0/24
