version: '3'
services:
    app:
        env_file:
            - .env
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        container_name: app-${APP_NAME}
        ports:
            - "${FORWARD_PHP_PORT:-9000}:9000"
        tty: true
        environment:
            APP_ENV: local
            PHP_IDE_CONFIG: "serverName=dev-test"
            WWWUSER: '${WWWUSER}'
            COMPOSER_ALLOW_SUPERUSER: 1
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        working_dir: /var/www/html
        logging:
            driver: "json-file"
            options:
                max-size: "100m"
                max-file: "10"
        volumes:
            - ./:/var/www/html:rw
            - ./nginx/custom.ini:/usr/local/etc/php/conf.d/custom.ini
        networks:
            - sail
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        depends_on:
            - mysql

    nginx:
        image: nginx:alpine
        container_name: nginx-${APP_NAME}
        logging:
            driver: "json-file"
            options:
                max-size: "100m"
                max-file: "10"
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www/html
            - ./nginx/conf.d/:/etc/nginx/conf.d/
            - ./nginx/ssl/:/etc/nginx/ssl/
        networks:
            - sail
        depends_on:
            - app
            - mysql

    mysql:
        image: "mariadb:${MARIADB_VERSION}"
        container_name: mysql-${APP_NAME}
        tty: true
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
            TZ: "America/Sao_Paulo"
        networks:
            - sail
        volumes:
            - 'sail-mariadb:/var/lib/mysql'
            - './create-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
            retries: 3
            timeout: 5s
        # env_file:
        #   - .env

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8082:80
        environment:
            PMA_HOSTS: mysql
            PMA_PASSWORD: "${DB_PASSWORD}"
            UPLOAD_LIMIT: 64M
        networks:
            - sail

    mailhog:
        image: 'mailhog/mailhog:latest'
        container_name: 'mailhog-${APP_NAME}'
        logging:
            driver: 'none' # disable saving logs
        environment:
            MH_AUTH_FILE: /mailhog.auth
            MH_MAILDIR_PATH: /data
            MH_STORAGE: maildir
        volumes:
            - ./mailhog.auth:/mailhog.auth:ro
            - ./data:/data:rw
        ports:
            - '${FORWARD_MAILHOG_PORT:-1025}:1025'
            - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
        networks:
            - sail

networks:
    sail:
        driver: bridge
volumes:
    sail-mariadb:
        driver: local
